### ISSUE TITLE
Youtube Cast

### ISSUE THREAD

**Issue by ophirpeleg** [ayufan-pine64/android-7.0#11]
Hello, 
I tried to connect my iPhone 6 to the Youtube and play from the iPhone videos, I click on the TV icon in youtube app and it saying "Connecting to TV..." and after 5 seconds it disapper... 
But from my computer (Windows 10) it works fine.

**Comment by ayufan** [comment]
Google Cast will not work due to missing Google certificates.

**Comment by ophirpeleg** [comment]
What do you mean? 
I will work sometime soon?
