### ISSUE TITLE
android-7.0-pine-a64-tv-v1.8-r56.img.gz does not work

### ISSUE THREAD

**Issue by Ylinen** [ayufan-pine64/android-7.0#14]
When you put this image on a card and boot the device, it does not work. You get a green/white screen of garbage.  Never shows the Google boot animation.

**Comment by ayufan** [comment]
Are you sure that this is 56? 56 works ok for me

**Comment by Ylinen** [comment]
Good catch.  I had 55.  Downloading now and will try. Others had same problem on Pine64 forum.
