### ISSUE TITLE
Super Su Binary Update and Pine64 stopped booting

### ISSUE THREAD

**Issue by mbt28** [ayufan-pine64/android-7.0#16]
Hello,

After Super Su binary update pine64 stopped booting. What should I do to fix it?

Thanks

**Comment by ayufan** [comment]
Yes, this is known problem and it's advised to not do it in first place.

It is potentially possible to fix that if you have adb shell access:

```
adb connect IP
adb root
adb connect IP
adb remount
adb shell
$ cd /system/bin
$ rm app_process app_process64
$ mv app_process64_original app_process64
$ mv app_process_init app_process
$ sync
$ reboot
```
