### ISSUE TITLE
1.13.8

### ISSUE THREAD

**Issue by LizzAcoreX** [ayufan-pine64/android-7.0#19]
No Boot, i don't have any Video or Sound.
The TV says "The HDMI resouliton is not supported"
Back to 1.11 and it works.

How can I use Netflix?
Version 3.35 says "No Supported Device".

Please Help :)

**Comment by LizzAcoreX** [comment]
does the 1.13.8 works for Pine A64 or are the Builds still Broken?

**Comment by ayufan** [comment]
The latest release from 7.1 should work with Pine A64.
