### ISSUE TITLE
Pine64 Touchscreen "works", but only for long press

### ISSUE THREAD

**Issue by kwiksand** [ayufan-pine64/android-7.0#2]
Hi, 

Great work on the android-7.0, I've been playing around with the LCD + Touchscreen Pine64 but with usb keyboard and mouse plugged in.  At first I thought the touch panel wasn't working at all, but then noticed that longpress works (i.e brining up the wallpaper/widget menu on home screen).

Obviously, you've said it "might" work but didn't/couldn't know for sure as you don't have the touch panel to test yourself, but thought I'd send in the issue anyway.  I'm fairly experienced with ROM installation/tweaks to configs/sound/wifi/etc, but from a phone point of view the the touchscreen is usually the bit that works (otherwise would be very hard to interface with at all, due to lack of keyboard).

Any parameters I can tweak in uEnv.txt to specify touch/interface type? or any further testing I can do to assist?  I can't see anything obvious in the logcat output, but perhaps android thinks the device is fine (as it partly works, that is) and hasn't failed completely

Thanks for the great work, regardless

**Comment by kwiksand** [comment]
Apologies, ended up reading the rest of the forum thread (missed a few pages in the middle), and can see it's been reported before

**Comment by ayufan** [comment]
I tested. The latest build does support touches OK.

**Comment by kwiksand** [comment]
Thanks again
