### ISSUE TITLE
720p resolution

### ISSUE THREAD

**Issue by drindrin4** [ayufan-pine64/android-7.0#4]

**Comment by DJFliX** [comment]
What do you mean exactly? Do you want 720p resolution? Is your pine forced into 720p resolution? Or do you have issues with streaming DRM-protected content in a resolution of 720p (and higher)?

**Comment by drindrin4** [comment]
I mean hdmi screen  resolution. default pine64.org image (andr 5.1) can switch to 720p in terminal. This resolution more situable for this hardware (frezze fallout shelter - for example).

**Comment by starcrescent** [comment]
I second for 720p resolution. If 4k or 1080p is not supported by screen it should detect automatically and switch to 720p.

**Comment by drindrin4** [comment]
that good, but 720p more suitable for this hardware. there may be a terminal command or /etc/init script?

**Comment by ayufan** [comment]
It is hard to make auto-detect of resolution. Currently the resolution is hardcoded to 1080p. You can freely change that later to be 720p.

**Comment by drindrin4** [comment]
change in soorce code?

**Comment by maumoura** [comment]
Hi, I'd also like to know where exactly can we change the default resolution to be 720p.

I tried changing the uEnv.txt file in the boot partition. I've added `disp.screen0_output_mode=720p` to the `optargs` line (separated by a space in the end, leaving the other parameters untouched).
I've also tried the more specific 720p50 and 720p60 modes and their numeric values 4 and 5 as described here: [https://github.com/longsleep/sunxi-disp-tool](https://github.com/longsleep/sunxi-disp-tool), but none of these worked.

I'm not really sure that these parameters also apply to the kernel in question. Anything I'm missing?

**Comment by ayufan** [comment]
It will be configurable with uEnv.txt

**Comment by drindrin4** [comment]
this
optargs=enforcing=0 cma=384M no_console_suspend disp.screen0_output_mode=720p
or
optargs=enforcing=0 cma=384M no_console_suspend disp.screen0_output_mode=720p60
not work

**Comment by ayufan** [comment]
It will be configurable in 1.8 build.

**Comment by drindrin4** [comment]
Thanks

**Comment by drindrin4** [comment]
[   20.039589] [BT_LPM] bluesleep_start: bluesleep_acquire irq
[   20.039589] 
[   20.053076] init: Starting service 'logd'...
[   20.064881] init: SELinux: Could not set context for /logger:  Read-only file system
[   20.076168] init: (Loading properties from /system/build.prop took 0.00s.)
[   20.083867] init: (Loading properties from /vendor/build.prop took 0.00s.)
[   20.091488] init: (Loading properties from /factory/factory.prop took 0.00s.)
[   20.099695] init: /recovery not specified in fstab
[   20.105557] logd.auditd: start
[   20.106118] init: Starting service 'debuggerd'...
[   20.107232] init: Starting service 'debuggerd64'...
[   20.108327] init: Starting service 'vold'...
[   20.124859] logd.klogd: 10845668337
[   20.129539] init: Not bootcharting.
[   20.823495] init: Starting service 'exec 2 (/system/bin/tzdatacheck)'...
[   20.847260] init: Service 'exec 2 (/system/bin/tzdatacheck)' (pid 1678) exited with status 0
[   20.859558] init: property_set("ro.bt.bdaddr_path", "/data/misc/bluetooth/bdaddr") failed
[   25.798380] init: do_start: Service bootclone not found
[   25.804355] init: Starting service 'precopy'...
[   25.811037] init: (Loading properties from /data/local.prop took 0.00s.)
[   25.815371] type=1400 audit(1262304022.780:16): avc: denied { read } for pid=1680 comm="precopy.sh" path="/sbin/busybox" dev="rootfs" ino=4125 scontext=u:r:preinstall:s0 tcontext=u:object_r:rootfs:s0 tclass=file permissive=1
[   25.816172] type=1400 audit(1262304022.780:17): avc: denied { getattr } for pid=1680 comm="precopy.sh" path="/data/system.notfirstrun.precopy" dev="mmcblk0p4" ino=57 scontext=u:r:preinstall:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[   26.052068] init: Service 'precopy' (pid 1680) exited with status 0
[   26.059507] init: Starting service 'logd-reinit'...
[   26.070981] init: Starting service 'healthd'...
[   26.076782] init: cannot find '/system/bin/tee_supplicant' (No such file or directory), disabling 'optee'
[   26.079694] binder: 1682:1682 transaction failed 29189, size 0-0
[   26.081460] logd.daemon: reinit
[   26.097450] init: Starting service 'watchdogd'...
[   26.103994] init: Starting service 'lmkd'...
[   26.105742] watchdogd: started (interval 60, margin 20)!
[   26.105817] watchdogd: Failed to open /dev/watchdog: No such file or directory
[   26.123834] init: Starting service 'servicemanager'...
[   26.130772] init: Starting service 'surfaceflinger'...
[   26.137248] init: couldn't write 1686 to /sys/fs/cgroup/stune/foreground/tasks: No such file or directory
[   26.137397] init: Service 'logd-reinit' (pid 1681) exited with status 0
[   26.137543] init: Service 'watchdogd' (pid 1683) exited with status 1
[   26.140179] init: Starting service 'exec 3 (/sbin/busybox)'...
[   26.168765] type=1400 audit(1262304023.120:18): avc: denied { transition } for pid=1687 comm="init" path="/sbin/busybox" dev="rootfs" ino=4125 scontext=u:r:init:s0 tcontext=u:r:su:s0 tclass=process permissive=1
[   26.190494] type=1400 audit(1262304023.120:19): avc: denied { rlimitinh } for pid=1687 comm="busybox" scontext=u:r:init:s0 tcontext=u:r:su:s0 tclass=process permissive=1
[   26.207416] type=1400 audit(1262304023.120:20): avc: denied { siginh } for pid=1687 comm="busybox" scontext=u:r:init:s0 tcontext=u:r:su:s0 tclass=process permissive=1
[   26.228122] type=1400 audit(1262304023.120:21): avc: denied { noatsecure } for pid=1687 comm="busybox" scontext=u:r:init:s0 tcontext=u:r:su:s0 tclass=process permissive=1
[   26.246557] init: Service 'exec 3 (/sbin/busybox)' (pid 1687) exited with status 0
[   26.255007] init: Starting service 'exec 4 (/sbin/busybox)'...
[   26.264956] init: Service 'exec 4 (/sbin/busybox)' (pid 1690) exited with status 2
[   26.284649] init: Service zygote does not have a SELinux domain defined.
[   26.292707] init: Starting service 'zygote_secondary'...
[   26.303322] type=1400 audit(1262304023.280:22): avc: denied { write } for pid=1 comm="init" name="tracing_on" dev="debugfs" ino=177 scontext=u:r:init:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=1
[   26.304042] init: Starting service 'console'...
[   26.305055] init: Starting service 'exec 5 (/system/bin/ifconfig)'...
tulip-chiphd:/ # [   26.566486] [DISP] disp_ioctl,line:1612:para err in disp_ioctl, cmd = 0xb,screen id = 0
[   26.584580] type=1400 audit(1262304023.560:23): avc: denied { write } for pid=1686 comm="surfaceflinger" name="trace_marker" dev="debugfs" ino=174 scontext=u:r:surfaceflinger:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=1
[   26.607795] type=1400 audit(1262304023.560:24): avc: denied { open } for pid=1686 comm="surfaceflinger" path="/sys/kernel/debug/tracing/trace_marker" dev="debugfs" ino=174 scontext=u:r:surfaceflinger:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=1
[   26.636424] libphy: 1c30000.eth: probed
[   26.638508] init: Starting service 'bootanim'...
[   26.682830] sunxi-gmac 1c30000.eth eth0: eth0: PHY ID 001cc915 at 0 IRQ poll (1c30000.eth-0:00)
[   26.705948] init: Service 'exec 5 (/system/bin/ifconfig)' (pid 1695) exited with status 0
[   26.715637] init: Starting service 'exec 6 (/system/bin/ethtool)'...
[   27.029636] init: Service 'exec 6 (/system/bin/ethtool)' (pid 1723) exited with status 0
[   27.038882] init: cannot find '/system/bin/update_verifier' (No such file or directory), disabling 'exec 7 (/system/bin/update_verifier)'
[   27.053445] init: Service flash_recovery does not have a SELinux domain defined.
[   27.062353] init: Service zygote does not have a SELinux domain defined.
[   27.066447] healthd: BatteryFullChargePath not found
[   27.066461] healthd: BatteryCycleCountPath not found
[   27.081618] init: Starting service 'audioserver'...
[   27.088226] init: Starting service 'cameraserver'...
[   27.095340] init: Starting service 'drm'...
[   27.101168] init: Starting service 'installd'...
[   27.107935] init: Starting service 'keystore'...
[   27.114208] init: Starting service 'mediacodec'...
[   27.121130] init: Starting service 'mediadrm'...
[   27.127994] init: Starting service 'mediaextractor'...
[   27.134854] init: Starting service 'media'...
[   27.141394] init: Starting service 'netd'...
[   27.147315] init: Starting service 'ril-daemon'...
[   27.153859] init: Starting service 'gatekeeperd'...
[   27.161027] init: Starting service 'perfprofd'...
[   27.180859] init: Starting service 'exec 8 (/system/bin/ifconfig)'...
[   27.206513] init: Service 'exec 8 (/system/bin/ifconfig)' (pid 1766) exited with status 0
[   27.215637] init: Starting service 'exec 9 (/system/bin/ethtool)'...
[   27.235642] init: Service 'exec 9 (/system/bin/ethtool)' (pid 1769) exited with status 0
[   27.247269] init: Starting service 'exec 10 (/system/bin/ifconfig)'...
[   27.272563] init: Service 'exec 10 (/system/bin/ifconfig)' (pid 1772) exited with status 0
[   27.281818] init: Starting service 'exec 11 (/system/bin/ethtool)'...
[   27.301122] init: Service 'exec 11 (/system/bin/ethtool)' (pid 1775) exited with status 0
[   27.310716] android_usb: already disabled
[   27.315586] init: Starting service 'adbd'...
[   27.325795] adb_open
[   27.328194] mtp_bind_config
[   27.331246] gadget_is_softwinner_otg is not -int
[   27.336759] gadget_is_softwinner_otg is not -int
[   27.341839] [sw_udc]: alloc request: ep(0xffffffc000b281b8, ep1in-bulk, 512), req(0xffffffc03b2ce840)
[   27.351938] [sw_udc]: alloc request: ep(0xffffffc000b281b8, ep1in-bulk, 512), req(0xffffffc03b2ce7c0)
[   27.362425] [sw_udc]: alloc request: ep(0xffffffc000b281b8, ep1in-bulk, 512), req(0xffffffc03b2ce740)
[   27.372876] [sw_udc]: alloc request: ep(0xffffffc000b281b8, ep1in-bulk, 512), req(0xffffffc03b2ce6c0)
[   27.382983] [sw_udc]: alloc request: ep(0xffffffc000b28238, ep1out-bulk, 512), req(0xffffffc03b2ce640)
[   27.393518] [sw_udc]: alloc request: ep(0xffffffc000b28238, ep1out-bulk, 512), req(0xffffffc03b2ce5c0)
[   27.404051] [sw_udc]: alloc request: ep(0xffffffc000b28438, ep4-int, 512), req(0xffffffc03b2ce540)
[   27.413865] [sw_udc]: alloc request: ep(0xffffffc000b28438, ep4-int, 512), req(0xffffffc03b2ce4c0)
[   27.424030] [sw_udc]: alloc request: ep(0xffffffc000b28438, ep4-int, 512), req(0xffffffc03b2ce440)
[   27.433840] [sw_udc]: alloc request: ep(0xffffffc000b28438, ep4-int, 512), req(0xffffffc03b2ce3c0)
[   27.443977] [sw_udc]: alloc request: ep(0xffffffc000b28438, ep4-int, 512), req(0xffffffc03b2ce340)
[   27.454120] adb_bind_config
[   27.457173] [sw_udc]: alloc request: ep(0xffffffc000b28338, ep2out-bulk, 512), req(0xffffffc03b2ce2c0)
[   27.467730] [sw_udc]: alloc request: ep(0xffffffc000b282b8, ep2in-bulk, 512), req(0xffffffc03b2ce240)
[   27.477862] [sw_udc]: alloc request: ep(0xffffffc000b282b8, ep2in-bulk, 512), req(0xffffffc03b2ce1c0)
[   27.488320] [sw_udc]: alloc request: ep(0xffffffc000b282b8, ep2in-bulk, 512), req(0xffffffc03b2ce140)
[   27.498453] [sw_udc]: alloc request: ep(0xffffffc000b282b8, ep2in-bulk, 512), req(0xffffffc03b2ce0c0)
[   27.508919] [sw_udc]: sunxi_udc_pullup, is_on = 1
[   27.514071] [sw_udc]: sunxi_udc_set_pullup_2337: usb device is not active
[   29.351197] type=1400 audit(1262304026.380:25): avc: denied { write } for pid=1923 comm="AudioOut_D" name="trace_marker" dev="debugfs" ino=174 scontext=u:r:audioserver:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=1
[   29.375249] type=1400 audit(1262304026.380:26): avc: denied { open } for pid=1923 comm="AudioOut_D" path="/sys/kernel/debug/tracing/trace_marker" dev="debugfs" ino=174 scontext=u:r:audioserver:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=1
[   29.634786] libphy: 1c30000.eth-0:00 - Link is Up - 1000/Full
[   30.033095] type=1400 audit(1262304027.070:27): avc: denied { write } for pid=1971 comm="BootAnimation" name="trace_marker" dev="debugfs" ino=174 scontext=u:r:bootanim:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=1
[   30.066381] type=1400 audit(1262304027.070:28): avc: denied { open } for pid=1971 comm="BootAnimation" path="/sys/kernel/debug/tracing/trace_marker" dev="debugfs" ino=174 scontext=u:r:bootanim:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=1
[   31.684653] type=1400 audit(1262304028.750:29): avc: denied { write } for pid=1748 comm="cameraserver" name="trace_marker" dev="debugfs" ino=174 scontext=u:r:cameraserver:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=1
[   31.708196] type=1400 audit(1262304028.750:30): avc: denied { open } for pid=1748 comm="cameraserver" path="/sys/kernel/debug/tracing/trace_marker" dev="debugfs" ino=174 scontext=u:r:cameraserver:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=1
[   31.836912] type=1400 audit(1262304028.900:31): avc: denied { write } for pid=1691 comm="zygote" name="trace_marker" dev="debugfs" ino=174 scontext=u:r:zygote:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=1
[   31.859586] type=1400 audit(1262304028.900:32): avc: denied { open } for pid=1691 comm="zygote" path="/sys/kernel/debug/tracing/trace_marker" dev="debugfs" ino=174 scontext=u:r:zygote:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=1
[   32.097737] alloc_contig_range test_pages_isolated(60077, 603fb) failed
[   37.157327] warning: `main' uses 32-bit capabilities (legacy support in use)
[   86.105801] healthd: battery none chg=a
[   95.464223] hdmi_clk_disable_prepare()L196
[  111.119637] hdmi_clk_enable_prepare()L181
[  133.746279] nf_conntrack: automatic helper assignment is deprecated and it will be removed soon. Use the iptables CT target to attach helpers instead.
[  145.145693] healthd: battery none chg=a
[  150.560967] qtaguid: iface_stat: stat_update() eth0 not found
