### ISSUE TITLE
TV edition doesn't override build.prop settings

### ISSUE THREAD

**Issue by mikey0000** [ayufan-pine64/android-7.0#5]
At least from what I've seen so far (I am mostly building from source) the overrides aren't overriding hence the issues with the play store.

**Comment by ayufan** [comment]
Strange, because it seems that overrides do work, because we execute them before, before `system/build.prop`. The issue with play store seems to be a different.

**Comment by mikey0000** [comment]
Oh right, was expecting build.prop to be changed, been manually setting to fugu :P

**Comment by ayufan** [comment]
I have this plan to load part of the settings from `BOOT` partition to make it much easier to tune.
