### ISSUE TITLE
Pairing with Android TV Remote app not possible

### ISSUE THREAD

**Issue by DJFliX** [ayufan-pine64/android-7.0#6]
When I try to pair the device it seems that bluetooth is not functional. The Android TV app (running on my Xperia Z3, Android 7.0 DP4) does not recognise the Pine64 machine and I'm not able to pair. 

I have also not been able to bring up a list of bluetooth devices in the 'add accessory/remote' section of the Settings app. I believe this is related to the above. What kind of diagnostic steps can I take to further identify the issue at hand?

**Comment by ayufan** [comment]
Hmm, I use Android TV on iOS and used that on Android, but it required to be on the same WiFi connection in order to make it work.

**Comment by DJFliX** [comment]
I've connected the Pine64 using Ethernet to my TP-Link Archer C7 (running LEDE) as well as using WiFi. On both cases my phone was not able to detect the presence of the Pine64. Unfortunately I don't have an iOS device around. I updated to your 1.4 Alpha release but even then, no dice. I'll try to some wiresharking soon to check whether the Pine64 is actually broadcasting it's presence on the network.

**Comment by ayufan** [comment]
It's possible that Android TV Remote uses multicasts and your router can block them.

**Comment by ayufan** [comment]
Please open if you find more information.
