### ISSUE TITLE
LCD doesnt boot v1.7 R54

### ISSUE THREAD

**Issue by steschm0712** [ayufan-pine64/android-7.0#8]
Hello,
i installed the R54 image using windisk32 and everything boots fine while using HDMI but when i edit uEnv.txt and uncomment the line:
fdt_filename_prefix=pine64/sun50i-a64-lcd-
pine doesnt boot anymore. LCD stays dark and sometimes after 15 seconds the red power led is off.

any ideas why?

thx
br
Stefan

**Comment by ayufan** [comment]
I did test that. It works. Make sure that you disconnect HDMI.

**Comment by steschm0712** [comment]
it works now but the problem is related to the camera. When the camera is connected i have the above problem. the board only runs for 15 seconds and then turn off completly.

when i disconnect the camera its working.
